[package]
name = "spaday"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.14.1"
clap = { version = "4.5.20", features = ["derive"] }
exe = "0.5.6"
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.132"
